
### get all
GET http://localhost:9002/users

### login
POST http://localhost:9002/users/login
content-type: application/json

{
    "mail": "tomalebgdu69@gmail.com",
    "password": "pass"
}

### register user
POST http://localhost:9002/users/register
Content-Type: application/json

{
    "surname": "Le nom",
    "firstName": "le prénom",
    "nickname":"pseudoLa",
    "address" : "Rue de la street 43, 4444 Bxl",
    "mail": "pseudoLa@gmail.com",
    "password" : "password"
}


### login user
POST http://localhost:9002/users/login
Content-Type: application/json

{
    "mail": "pseudoLa@gmail.com",
    "password": "password"
}

### delete user
DELETE http://localhost:9002/users/2

### delete user - bad id
DELETE http://localhost:9002/users/984

### update user
PUT http://localhost:9002/users/2
Content-Type: application/json

{
    "surname": "Le nom - modified",
    "firstName": "le prénom - modified",
    "nickname":"pseudoLa - modified",
    "address" : "OUI-Rue de la street 43, 4444 Bxl",
    "mail": "modified@gmail.com",
    "password" : "allloooooo"
}

### login modified user
POST http://localhost:9002/users/login
Content-Type: application/json

{
    "mail": "modified@gmail.com",
    "password": "allloooooo"
}

### update user - wrong id
PUT http://localhost:9002/users/9489
Content-Type: application/json

{
    "surname": "Le nom - modified",
    "firstName": "le prénom - modified",
    "nickname":"pseudoLa - modified",
    "address" : "OUI-Rue de la street 43, 4444 Bxl",
    "mail": "modified@gmail.com",
    "password" : "allloooooo"
}

### update user - one field
PUT http://localhost:9002/users/2
Content-Type: application/json

{
    "surname": "Le nom - modified2"
}


### get by email
GET http://localhost:9002/users/modified@gmail.com